export const movies = [
    {
        id: 0,
        imageSrc: "/Images/assets/Square_Eyes_Cover1.jpeg",
        title: 'Hobbs & Shaw',
        description: `Lawman Luke Hobbs (Dwayne "The Rock" Johnson) and outcast Deckard Shaw (Jason Statham) form an unlikely alliance when a cyber-genetically enhanced villain threatens the future of humanity.`,
        mostPopular: true,
        newRelease: true,
        action: true,
    },
    {
        id: 1,
        imageSrc: "/Images/assets/Square_Eyes_Cover2.jpeg",
        title: 'Godzilla',
        description: `The crypto-zoological agency Monarch faces off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah.`,
        mostPopular: true,
        newRelease: true,
        action: true,
    },
    {
        id: 2,
        imageSrc: "/Images/assets/Square_Eyes_Cover3.jpeg",
        title: 'Once upon a time in Hollywood',
        description: `A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.`,
        mostPopular: true,
        newRelease: true,
        comedy: true,
    },
    {
        id: 3,
        imageSrc: "/Images/assets/Square_Eyes_Cover4.jpeg",
        title: 'Scream',
        description: `25 years after a streak of brutal murders shocked the quiet town of Woodsboro, Calif., a new killer dons the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past.`,
        mostPopular: true,
        newRelease: true,
        drama: true,
    },
    {
        id: 4,
        imageSrc: "/Images/assets/Square_Eyes_Cover5.jpeg",
        title: 'Sweetheart',
        description: `Jenn has washed ashore a small tropical island and it doesn't take her long to realize she's completely alone. She must spend her days not only surviving the elements, but must also fend off the malevolent force that comes out each night.`,
        mostPopular: true,
        newRelease: true,
        drama: true,
    },
    {
        id: 5,
        imageSrc: "/Images/assets/Square_Eyes_Cover6.jpeg",
        title: 'The Adams family',
        description: `The eccentrically macabre family moves to a bland suburb where Wednesday Addams' friendship with the daughter of a hostile and conformist local reality show host exacerbates conflict between the families.`,
        mostPopular: true,
        newRelease: true,
        comedy: true,
    },
    {
        id: 6,
        imageSrc: "/Images/assets/Square_Eyes_Cover7.jpeg",
        title: 'Batman',
        description: `When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.`,
        mostPopular: true,
        newRelease: true,
        action: true,
    },
    {
        id: 7,
        imageSrc: "/Images/assets/Square_Eyes_Cover8.jpeg",
        title: 'Toy Story 4',
        description: `When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.`,
        mostPopular: true,
        newRelease: true,
        comedy: true,
    }
]